language: android

dist: trusty

android:
  components:
    - platform-tools
    - build-tools-30.0.2
    - android-30
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew build