language: android

dist: trusty

cache:
  directories:
    - $TRAVIS_BUILD_DIR/.gradle

addons:
  browserstack:
    username: "benediktlanger_94Ay0H"
    access_key:
      secure: "DkROjGyBUnQa/uvaEl4Wi3eg5dp+ywjkeJaUU5lWj8aE5Cq0xnM/5MZHpmViflrmdI1VNXFVBXYJ8spt/EMsk+ziYVa2ugY6NGi7WCQ8ZcwtGA7WVPybJ8AUCyTsWbYwy0GjEl521HS7AzC974WgMgSgk2wOQlyNbZh9Qlnqu/P6VbwqEBflTd7swgrhaU/oNafAw266LNx/JbZLDiR1ucA/JV6cEw4rV4mGM+u1FcI7xEvi1fsh8YVxgbhHG4Ha+wWgqb1HLSHwQvMxL24FJdFUK+RzSCzbxqVfBrq/XmlHQPfEYXB9539zyg1BmB2y5JTYQztcFfEfLiD11AzKcnVOt/NRate3TFFi7MBgrrMIXEookDUBJ6RuHwYv2yW3vE2MvC63z1INR4MyGpOByLUSenp1BtnQSWLCgI6Gbn1TOTlRs7DmP1wdGaGKBmKmOQB5Y0ZUhdRnC1q6gc3V6xP8v6DLxb57tvfpXrneE/hb8/CVpQf8wGMphEUfV4k3yyXbeayaLHuYzh1WOUuoTdzy8A+9FqxCAQ7PDVTAha4yliQAD+AbKIojKsIxyoVtH2A5EA2RtTHFW7xOAADt9WbW76qbYL8hnkqB7liwD5BvB6EyfAUrcgH8wlmW6ZwAZwINR/PFTPltT8JAMuxEMiS/AXmSx5MQVsAO53EhFt0="
    app_path: "app/build/outputs/apk/debug/app-debug.apk"

android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - build-tools-30.0.2
    - android-30

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-30"

  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk14
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 14 --target $JAVA_HOME
  - wget https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh
  - bash install.sh
  - nvm install 16
  - nvm list
  - node -v

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script:
        - ./gradlew test
    - script:
        - echo "Entering Integration Testing"
      name: "Integration Tests"
    - script:
        - echo "Entering UI-Testing"
      name: "UI Tests"
    - install:
        - ./gradlew clean assembleDebug
      script:
        - node ./AppiumTests/index.js
      name: "Appium Tests"
