language: android

dist: trusty


android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - build-tools-30.0.2
    - android-30

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-30"


script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk14
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 14 --target $JAVA_HOME
  - ./gradlew test