language: android

dist: trusty

env:
  matrix:
    - TRAVIS_JDK=adopt-openj9@1.14

android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - build-tools-30.0.2
    - android-30

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-30"


script:
  - ./gradlew test