language: android

dist: trusty

android:
  components:
    - build-tools;30.0.2
    - platforms;android-30
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'

script:
  - ./gradlew build