language: android

dist: trusty

jdk:
  - openjdk14

android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - build-tools-30.0.2
    - android-30

before_install:
  - chmod +x gradlew


script:
  - jdk_switcher use openjdk14
  - ./gradlew test